### PR TITLE
fix: adapt to new callback tracking

### PR DESCRIPTION
**Pull request by JimLarson**
Refs: Agoric/agoric-sdk#6305

## Description

Make changes to `committing_client` corresponding to those in `local_client` in tendermint/tendermint#8331.

### CODE REVIEW

**Review by ivanlei — COMMENTED** [review]
~Did we previously integrate most of the upstream https://github.com/tendermint/tendermint/pull/8331 into our fork but miss a few lines in [abci/client/committing_client.go](https://github.com/agoric-labs/tendermint/pull/34/files#diff-17f3be5278f95fbd15a6cb17a80293b2fbe41e294e4a7b5fba1914cc50e30818)~

_Update: OIC we added `committingClient` and it wasn't in line with the changes to `ReqRes`_

**Review by ivanlei — COMMENTED** [review]
Do we have CI setup on Agoric's fork of tendermint? Seems like CI would be helpful to validate new changes don't introduce bugs.

**Review by michaelfig — APPROVED** [review]
LGTM!

**Comment by JimLarson** [comment]
Recorded a TODO for enabling CI in Agoric/agoric-sdk#6933

**Pull request merged**
